apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-caching-reddit-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-caching-reddit
  template:
    metadata:
      labels:
        app: app-caching-reddit
    spec:
      containers:
        - name: appcachingreddit-cd-containerapp
          image: mydockerhubidm/redditcaching:1.0.0-69
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
