apiVersion: apps/v1
kind: Deployment
metadata:
  name: AppCachingReddit-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app:AppCachingReddit-cd
  template:
    metadata:
      labels:
        app: AppCachingReddit-cd
    spec:
      containers:
        - name: AppCachingReddit-cd-containerapp
          image: mydockerhubidm/redditcaching:1.0.0-69
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
