apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-firstapp-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-firstapp-cd
  template:
    metadata:
      labels:
        app: my-firstapp-cd
    spec:
      containers:
        - name: my-firstapp-cd-containerapp
          image: mydockerhubidm/my-firstapp-ci:1.0.0-20
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
