apiVersion: apps/v1
kind: Deployment
metadata:
  name: redditcaching-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redditcaching-cd
  template:
    metadata:
      labels:
        app: redditcaching-cd
    spec:
      containers:
        - name: redditcaching-cd-containerapp
          image: mydockerhubidm/redditcaching:1.0.0-20
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
