apiVersion: v1
kind: Service
metadata:
  name: app-caching-reddit-svc
  labels:
    app: app-caching-reddit-scv
spec:
  selector:
    app: app-caching-reddit

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
