apiVersion: v1
kind: Service
metadata:
  name: AppCachingReddit-cd
  labels:
    app: AppCachingReddit-cd
spec:
  selector:
    app: AppCachingReddit-cd

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
